# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(194, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Raleway Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"border-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"font: 87 8pt \"Raleway Black\";\n"
"font-size: 28pt;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(194, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("QLabel {\n"
"\n"
"    font: 63 12pt \"Raleway SemiBold\";\n"
"    margin-right: 15px;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setContentsMargins(0, 0, 30, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelUsername = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.labelUsername.setFont(font)
        self.labelUsername.setStyleSheet("")
        self.labelUsername.setWordWrap(False)
        self.labelUsername.setObjectName("labelUsername")
        self.gridLayout_4.addWidget(self.labelUsername, 0, 1, 1, 1)
        self.labelUsername_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.labelUsername_2.setFont(font)
        self.labelUsername_2.setStyleSheet("")
        self.labelUsername_2.setObjectName("labelUsername_2")
        self.gridLayout_4.addWidget(self.labelUsername_2, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 0, 1, 1)
        self.entryPassword = QtWidgets.QLineEdit(self.frame_2)
        self.entryPassword.setMaximumSize(QtCore.QSize(150, 16777215))
        self.entryPassword.setStyleSheet("font-size: 12pt;\n"
";")
        self.entryPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.entryPassword.setObjectName("entryPassword")
        self.gridLayout_4.addWidget(self.entryPassword, 1, 2, 1, 1)
        self.entryUsername = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryUsername.sizePolicy().hasHeightForWidth())
        self.entryUsername.setSizePolicy(sizePolicy)
        self.entryUsername.setMaximumSize(QtCore.QSize(150, 16777215))
        self.entryUsername.setTabletTracking(False)
        self.entryUsername.setAutoFillBackground(False)
        self.entryUsername.setStyleSheet("font-size: 12pt;\n"
"")
        self.entryUsername.setFrame(True)
        self.entryUsername.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.entryUsername.setDragEnabled(True)
        self.entryUsername.setObjectName("entryUsername")
        self.gridLayout_4.addWidget(self.entryUsername, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("QPushButton{    \n"
"    font: 63 12pt \"Raleway SemiBold\";\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    width: 60px;\n"
"    height: 30px;\n"
"    font-size: 12px;\n"
"    text-align: center;\n"
"    line-height: 20px;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(80, 160, 240);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 100)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cci_Bttn = QtWidgets.QPushButton(self.frame_3)
        self.cci_Bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cci_Bttn.setStyleSheet("")
        self.cci_Bttn.setObjectName("cci_Bttn")
        self.gridLayout_3.addWidget(self.cci_Bttn, 1, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 3, 1, 1)
        self.logInBttn = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logInBttn.sizePolicy().hasHeightForWidth())
        self.logInBttn.setSizePolicy(sizePolicy)
        self.logInBttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logInBttn.setStyleSheet("")
        self.logInBttn.setObjectName("logInBttn")
        self.gridLayout_3.addWidget(self.logInBttn, 0, 1, 1, 1)
        self.registerBttn = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerBttn.sizePolicy().hasHeightForWidth())
        self.registerBttn.setSizePolicy(sizePolicy)
        self.registerBttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerBttn.setStyleSheet("")
        self.registerBttn.setObjectName("registerBttn")
        self.gridLayout_3.addWidget(self.registerBttn, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Iniciar sesión"))
        self.labelUsername.setText(_translate("MainWindow", "Nombre usuario"))
        self.labelUsername_2.setText(_translate("MainWindow", "Contraseña"))
        self.cci_Bttn.setText(_translate("MainWindow", "Invitado"))
        self.logInBttn.setText(_translate("MainWindow", "Acceder"))
        self.registerBttn.setText(_translate("MainWindow", "Registro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
